name: Check YAML format
on:
  - pull_request
  - push

jobs:
  # Just check they are parseable at all for now.
  # In theory it might be nice to enforce a schema of some kind
  check-strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_version: 2.31.2
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: cache-yamlcheck-${{ runner.os }}-nix-store-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: cache-${{ runner.os }}-nix-store-

      - name: Print Strings
        run: |
          nix develop .#minimal --command ssmm-patcher print-strings

  check-credits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_version: 2.31.2
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: cache-yamlcheck-${{ runner.os }}-nix-store-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: cache-${{ runner.os }}-nix-store-

      - name: Print Strings
        run: |
          nix develop .#minimal --command ssmm-patcher print-strings -s credits.yaml

